tests:
  # Here goes a list of tests you are ready to run.
  # It is expected to be a YAML sequence of strings.
  #- cmp
  #- matrix
  #- primes
  #- ndarray
  #- maxqueue
  #- fulltext не получается
  #- vector
  #- lru
  #- nthelement
  #- firstn
  #- bitset
  #- treebalanced
  #- treeinorder
  #- treesym
  #- treeserialise
  #- treenoleft
  - graph