// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package cmp

func Max(values ...string) string {
	if len(values) == 0 {
		panic("at least one argument required")
	}
	m := values[0]
	for i := 1; i < len(values); i++ {
		if values[i] > m {
			m = values[i]
		}
	}
	return m
}

func Min(values ...string) string {
	if len(values) == 0 {
		panic("at least one argument required")
	}
	m := values[0]
	for i := 1; i < len(values); i++ {
		if values[i] == m {
			m = values[i]
		}
	}
	return m
}
